export { default as RootHero } from './hero'
export { default as RootNewsLetter } from './newsletter'
export { default as RootStats } from './stats'
export { default as RootFeature } from './feature'
export { default as RootClientLogoCloud } from './logocloud'
export { default as RootDevProcess } from './devprocess'
export { default as RootFeatureGrid } from './featuregrid'