// android, bash, dart, electron, flutter, gatsby, gcp, git, grafana, graphql, heroku, javascript, jenkins, jest, kotlin, linux, mariadb, mysql, nextjs, nginx, nodejs, nuxtjs, postgresql, postman, python, react, redis, sqlite, travisci, vuejs, vuepress, zapier

export const categories = [
  {
    title: "Programming Languages",
    items: [
      { name: "JavaScript", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/javascript.svg", url: "/services/software-development/javascript" },
      // HTML, CSS
      { name: "Python", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/python.svg", url: "/services/software-development/python" },
      { name: "SQL", icon: "https://www.vectorlogo.zone/logos/sqlite/sqlite-icon.svg", url: "/services/software-development/sql" },
      { name: "TypeScript", icon: "https://www.vectorlogo.zone/logos/typescriptlang/typescriptlang-icon.svg", url: "/services/software-development/typescript" },
      { name: "Bash", icon: "https://www.vectorlogo.zone/logos/gnu_bash/gnu_bash-icon.svg", url: "/services/software-development/bash" },
      { name: "Shell", icon: "https://raw.githubusercontent.com/steverichey/DockIcons/07ded5c45e6bf60b679c8ff543e3d50268d902e0/icons/console.svg", url: "/services/software-development/shell" },
      { name: "Java", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/java.svg", url: "/services/software-development/java" },
      { name: "C#", icon: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Logo_C_sharp.svg", url: "/services/software-development/c-sharp" },
      { name: "C++", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/c-plusplus.svg", url: "/services/software-development/cpp" },
      { name: "C", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/c.svg", url: "/services/software-development/c" },
      { name: "PHP", icon: "https://raw.githubusercontent.com/edent/SuperTinyIcons/d190e37443ed7a09f39017cbf06d1b6be82d06e1/images/svg/php.svg", url: "/services/software-development/php" },
      { name: "PowerShell", icon: "https://raw.githubusercontent.com/benc-uk/icon-collection/e33ee714d05a24a81cf6ccd967ef34b22cb77e65/azure-docs/logo_powershell.svg", url: "/services/software-development/powershell" },
      { name: "Go", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/go.svg", url: "/services/software-development/go" },
      { name: "Rust", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/rust.svg", url: "/services/software-development/rust" },
      { name: "Kotlin", icon: "https://www.vectorlogo.zone/logos/kotlinlang/kotlinlang-icon.svg", url: "/services/software-development/kotlin" },
      { name: "Ruby", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/ruby.svg", url: "/services/software-development/ruby" },
      { name: "Lua", icon: "https://www.vectorlogo.zone/logos/lua/lua-icon.svg", url: "/services/software-development/lua" },
      { name: "Dart", icon: "https://www.vectorlogo.zone/logos/dartlang/dartlang-icon.svg", url: "/services/software-development/dart" },

      // { name: "Assembly", icon: "https://upload.wikimedia.org/wikipedia/commons/0/00/AssemblyScript_logo_2020.svg", url: "/services/software-development/assembly" },
      // { name: "Swift", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/swift.svg", url: "/services/software-development/swift" },
      // { name: "R", icon: "https://www.vectorlogo.zone/logos/r-project/r-project-icon.svg", url: "/services/software-development/r" },
      // { name: "Visual Basic", icon: "https://www.vectorlogo.zone/logos/microsoft_vb/microsoft_vb-icon.svg", url: "/services/software-development/visual-basic" },
      // { name: "MATLAB", icon: "https://raw.githubusercontent.com/detain/svg-logos/07e36b4aa0691f3015886624395e083395e528c5/svg/m/matlab.svg", url: "/services/software-development/matlab" },
      // // - { name: "VBA", icon: "https://www.vectorlogo.zone/logos/microsoft_vb/microsoft_vb-icon.svg", url: "/services/software-development/vba" },
      // { name: "Groovy", icon: "https://www.vectorlogo.zone/logos/groovy-lang/groovy-lang-icon.svg", url: "/services/software-development/groovy" },
      // { name: "Delphi", icon: "https://upload.wikimedia.org/wikipedia/en/b/b2/Embarcadero_Delphi_10.4_Sydney_Product_Logo_and_Icon.svg", url: "/services/software-development/delphi" },
      // { name: "Scala", icon: "https://www.vectorlogo.zone/logos/scala-lang/scala-lang-icon.svg", url: "/services/software-development/scala" },
      // { name: "Perl", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/perl.svg", url: "/services/software-development/perl" },
      // { name: "Elixir", icon: "https://www.vectorlogo.zone/logos/elixir-lang/elixir-lang-icon.svg", url: "/services/software-development/elixir" },
      // { name: "Objective-C", icon: "https://www.vectorlogo.zone/logos/apple_objectivec/apple_objectivec-icon.svg", url: "/services/software-development/objective-c" },
      // { name: "Haskell", icon: "https://www.vectorlogo.zone/logos/haskell/haskell-icon.svg", url: "/services/software-development/haskell" },
      // { name: "GDScript", icon: "https://www.vectorlogo.zone/logos/godotengine/godotengine-icon.svg", url: "/services/software-development/gdscript" },
      // { name: "Lisp", icon: "https://www.vectorlogo.zone/logos/common-lispnet/common-lispnet-icon.svg", url: "/services/software-development/lisp" },
      // { name: "Solidity", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/solidity.svg", url: "/services/software-development/solidity" },
      // { name: "Clojure", icon: "https://www.vectorlogo.zone/logos/clojure/clojure-icon.svg", url: "/services/software-development/clojure" },
      // { name: "Julia", icon: "https://www.vectorlogo.zone/logos/julialang/julialang-icon.svg", url: "/services/software-development/julia" },
      // { name: "Erlang", icon: "https://www.vectorlogo.zone/logos/erlang/erlang-icon.svg", url: "/services/software-development/erlang" },
      // { name: "F#", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/fsharp.svg", url: "/services/software-development/fsharp" },
      // { name: "Fortran", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/fortran.svg", url: "/services/software-development/fortran" },
      // { name: "Prolog", icon: "https://raw.githubusercontent.com/vorillaz/devicons/ba75593fdf8d66496676a90cbf127d721f73e961/!SVG/prolog.svg", url: "/services/software-development/prolog" },
      // { name: "Zig", icon: "https://www.vectorlogo.zone/logos/ziglang/ziglang-icon.svg", url: "/services/software-development/zig" },
      { name: "Elm", icon: "https://www.vectorlogo.zone/logos/elm-lang/elm-lang-icon.svg", url: "/services/software-development/elm" },
      // { name: "Ada", icon: "https://www.vectorlogo.zone/logos/gnu_ada/gnu_ada-icon.svg", url: "/services/software-development/ada" },
      // { name: "OCaml", icon: "https://www.vectorlogo.zone/logos/ocaml/ocaml-icon.svg", url: "/services/software-development/ocaml" },
      // { name: "Apex", icon: "https://www.vectorlogo.zone/logos/salesforce_apex/salesforce_apex-icon.svg", url: "/services/software-development/apex" },
      // { name: "Cobol", icon: "https://www.vectorlogo.zone/logos/cobol/cobol-icon.svg", url: "/services/software-development/cobol" },
      // { name: "SAS", icon: "https://www.vectorlogo.zone/logos/sas/sas-icon.svg", url: "/services/software-development/sas" },
      // { name: "Crystal", icon: "https://www.vectorlogo.zone/logos/crystal-lang/crystal-lang-icon.svg", url: "/services/software-development/crystal" },
      // { name: "Nim", icon: "https://www.vectorlogo.zone/logos/nim-lang/nim-lang-icon.svg", url: "/services/software-development/nim" },
      // { name: "APL", icon: "https://www.vectorlogo.zone/logos/apl/apl-icon.svg", url: "/services/software-development/apl" },
      // { name: "Flow", icon: "https://www.vectorlogo.zone/logos/flowtype/flowtype-icon.svg", url: "/services/software-development/flow" },
      // { name: "Raku", icon: "https://www.vectorlogo.zone/logos/raku/raku-icon.svg", url: "/services/software-development/raku" },

      // ? {name: "Scheme", icon: "https://www.vectorlogo.zone/logos/scheme/scheme-icon.svg", url: "/services/software-development/scheme"},
      // ? {name: "Smalltalk", icon: "https://www.vectorlogo.zone/logos/smalltalk/smalltalk-icon.svg", url: "/services/software-development/smalltalk"},
      // ? {name: "Verilog", icon: "https://www.vectorlogo.zone/logos/verilog/verilog-icon.svg", url: "/services/software-development/verilog"},
      // ? {name: "VHDL", icon: "https://www.vectorlogo.zone/logos/vhdl/vhdl-icon.svg", url: "/services/software-development/vhdl"},
      // ? {name: "COBOL", icon: "https://www.vectorlogo.zone/logos/cobol/cobol-icon.svg", url: "/services/software-development/cobol"},
      // ? {name: "ABAP", icon: "https://www.vectorlogo.zone/logos/sap/sap-icon.svg", url: "/services/software-development/abap"},
      // ? {name: "Q#", icon: "https://www.vectorlogo.zone/logos/microsoft/microsoft-icon.svg", url: "/services/software-development/qsharp"},
      // ? {name: "K", icon: "https://www.vectorlogo.zone/logos/k/k-icon.svg", url: "/services/software-development/k"},
      // ? {name: "Pascal", icon: "https://www.vectorlogo.zone/logos/pascal/pascal-icon.svg", url: "/services/software-development/pascal"},
    ],
  },
  {
    // title: "Full-Stack & Cross-platform Frameworks",
    title: "Web frameworks and technologies ",
    items: [
      { name: "Node.js", icon: "https://www.vectorlogo.zone/logos/nodejs/nodejs-icon.svg", url: "/services/software-development/nodejs" },
      { name: "React", icon: "https://www.vectorlogo.zone/logos/reactjs/reactjs-icon.svg", url: "/services/software-development/react" },
      { name: "jQuery", icon: "https://www.vectorlogo.zone/logos/jquery/jquery-icon.svg", url: "/services/software-development/jquery" },
      { name: "Express", icon: "https://www.vectorlogo.zone/logos/expressjs/expressjs-icon.svg", url: "/services/software-development/express" },
      { name: "Angular", icon: "https://www.vectorlogo.zone/logos/angular/angular-icon.svg", url: "/services/software-development/angular" },
      { name: "Next.js", icon: "https://cdn.worldvectorlogo.com/logos/next-js.svg", url: "/services/software-development/nextjs" },
      { name: "Microsoft .NET", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/dotnet.svg", url: "/services/software-development/dotnet" },
      { name: "Vue.js", icon: 'https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/vue.svg', url: "/services/software-development/vuejs" },
      { name: "Flask", icon: "https://www.vectorlogo.zone/logos/pocoo_flask/pocoo_flask-icon.svg", url: "/services/software-development/flask" },
      { name: "Spring", icon: "https://www.vectorlogo.zone/logos/springio/springio-icon.svg", url: "/services/software-development/spring" },
      { name: "Django", icon: "https://www.vectorlogo.zone/logos/djangoproject/djangoproject-icon.svg", url: "/services/software-development/django" },
      { name: "Laravel", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/laravel.svg", url: "/services/software-development/laravel" },
      { name: "FastAPI", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/fastapi-icon.svg", url: "/services/software-development/fastapi" },
      { name: "Svelte", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/svelte-icon.svg", url: "/services/software-development/svelte" },
      { name: "Ruby on Rails", icon: "https://raw.githubusercontent.com/dochne/wappalyzer/471c2fb0b093973c098bd1855b89c8cde4997479/src/images/icons/Ruby%20on%20Rails.svg", url: "/services/software-development/rubyonrails" },
      { name: "NestJS", icon: "https://www.vectorlogo.zone/logos/nestjs/nestjs-icon.svg", url: "/services/software-development/nestjs" },
      { name: "Blazor", icon: "https://raw.githubusercontent.com/detain/svg-logos/07e36b4aa0691f3015886624395e083395e528c5/svg/b/blazor.svg", url: "/services/software-development/blazor" },
      { name: "Nuxt.js", icon: "https://raw.githubusercontent.com/withastro/docs/42acee562f48ef2fbc33ff12a224a1ab5be4b7f9/public/logos/nuxtjs.svg", url: "/services/software-development/nuxtjs" },
      { name: "Symfony", icon: "https://www.vectorlogo.zone/logos/symfony/symfony-icon.svg", url: "/services/software-development/symfony" },
      { name: "Deno", icon: "https://www.vectorlogo.zone/logos/deno/deno-icon.svg", url: "/services/software-development/deno" },
      { name: "Gatsby", icon: "https://www.vectorlogo.zone/logos/gatsbyjs/gatsbyjs-icon.svg", url: "/services/software-development/gatsby" },
      { name: "Fastify", icon: "https://raw.githubusercontent.com/detain/svg-logos/07e36b4aa0691f3015886624395e083395e528c5/svg/f/fastify.svg", url: "/services/software-development/fastify" },
      { name: "Phoenix", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/phoenix.svg", url: "/services/software-development/phoenix" },
      { name: "CodeIgniter", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/codeigniter-icon.svg", url: "/services/software-development/codeigniter" },
      { name: "SolidJS", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/solidjs-icon.svg", url: "/services/software-development/solidjs" },
      { name: "Remix", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/remix-icon.svg", url: "/services/software-development/remix" },
      { name: "Play Framework", icon: "https://raw.githubusercontent.com/dochne/wappalyzer/471c2fb0b093973c098bd1855b89c8cde4997479/src/images/icons/Play.svg", url: "/services/software-development/play-framework" },
      { name: "Lit", icon: "https://raw.githubusercontent.com/dochne/wappalyzer/471c2fb0b093973c098bd1855b89c8cde4997479/src/images/icons/Lit.svg", url: "/services/software-development/lit" },
      { name: "Qwik", icon: "https://raw.githubusercontent.com/dochne/wappalyzer/471c2fb0b093973c098bd1855b89c8cde4997479/src/images/icons/Qwik.svg", url: "/services/software-development/qwik" },
      // // TODO: Move Flutter to Mobile Development
      // { name: "Flutter", icon: FlutterIcon },
      // { name: "And More", icon: BsThreeDots },
    ],
  },
  {
    title: "CMS & E-Commerce",
    items: [
      { name: "WordPress", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/wordpress-icon.svg", url: "/services/software-development/wordpress" },
      { name: "Drupal", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/drupal-icon.svg", url: "/services/software-development/drupal" },
    ],
  },
  // {
  //   title: "UI/UX & Frontend Tools, Technologies & Libraries",
  // NativeWind, TamaGUI, TailwindCSS, ETC.
  // },
  {
    title: "DevOps",
    items: [
      { name: "Docker", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/docker-icon.svg" },
      { name: "Kubernetes", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/kubernetes.svg" },
      { name: "GitLab CI/CD", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/gitlab.svg" },
      { name: "OpenShift", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/openshift.svg" },
      { name: "Grafana", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/grafana.svg" },
    ],
  },
  {
    title: "Clouds",
    items: [
      { name: "AWS", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/aws.svg" },
      { name: "Azure", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/microsoft-azure.svg" },
      { name: "Google Cloud", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/google-cloud.svg" },
      { name: "Akamai Cloud", icon: "https://raw.githubusercontent.com/dochne/wappalyzer/471c2fb0b093973c098bd1855b89c8cde4997479/src/images/icons/Akamai.svg" },
      { name: "DigitalOcean", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/digital-ocean-icon.svg" },
    ],
  },
  {
    title: "Cybersecurity",
    items: [
      { name: "Cloudflare", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/cloudflare-icon.svg" },
      { name: "Burp Suite", icon: "https://raw.githubusercontent.com/vinceliuice/Fluent-icon-theme/d56a03ec0d1be67353abbe293cb85a1ba25d2fad/src/scalable/apps/burp.svg" },
      { name: "Nmap", icon: "https://raw.githubusercontent.com/file-icons/icons/e6e6e6ac8cb1d91867167c228c00a667f4d47101/svg/Nmap.svg" },
      { name: "Wireshark", icon: "https://www.vectorlogo.zone/logos/wireshark/wireshark-icon.svg" },
      { name: "Metasploit", icon: "https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-icon-theme/f68510f72ebaa446a4d19133f3e8eee6288f7420/Papirus/64x64/apps/metasploit.svg" },
    ],
  },
];
