// android, bash, dart, electron, flutter, gatsby, gcp, git, grafana, graphql, heroku, javascript, jenkins, jest, kotlin, linux, mariadb, mysql, nextjs, nginx, nodejs, nuxtjs, postgresql, postman, python, react, redis, sqlite, travisci, vuejs, vuepress, zapier

export const categories = [
  {
    title: "Programming Languages",
    items: [
      { name: "JavaScript", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/javascript.svg", url: "/services/software-development/javascript" },
      // HTML, CSS
      { name: "Python", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/python.svg", url: "/services/software-development/python" },
      { name: "SQL", icon: "https://www.vectorlogo.zone/logos/sqlite/sqlite-icon.svg", url: "/services/software-development/sql" },
      { name: "TypeScript", icon: "https://www.vectorlogo.zone/logos/typescriptlang/typescriptlang-icon.svg", url: "/services/software-development/typescript" },
      { name: "Bash", icon: "https://www.vectorlogo.zone/logos/gnu_bash/gnu_bash-icon.svg", url: "/services/software-development/bash" },
      { name: "Shell", icon: "https://raw.githubusercontent.com/steverichey/DockIcons/07ded5c45e6bf60b679c8ff543e3d50268d902e0/icons/console.svg", url: "/services/software-development/shell" },
      { name: "Java", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/java.svg", url: "/services/software-development/java" },
      { name: "C#", icon: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Logo_C_sharp.svg", url: "/services/software-development/c-sharp" },
      { name: "C++", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/c-plusplus.svg", url: "/services/software-development/cpp" },
      { name: "C", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/c.svg", url: "/services/software-development/c" },
      { name: "PHP", icon: "https://raw.githubusercontent.com/edent/SuperTinyIcons/d190e37443ed7a09f39017cbf06d1b6be82d06e1/images/svg/php.svg", url: "/services/software-development/php" },
      { name: "PowerShell", icon: "https://raw.githubusercontent.com/benc-uk/icon-collection/e33ee714d05a24a81cf6ccd967ef34b22cb77e65/azure-docs/logo_powershell.svg", url: "/services/software-development/powershell" },
      { name: "Go", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/go.svg", url: "/services/software-development/go" },
      { name: "Rust", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/rust.svg", url: "/services/software-development/rust" },
      { name: "Kotlin", icon: "https://www.vectorlogo.zone/logos/kotlinlang/kotlinlang-icon.svg", url: "/services/software-development/kotlin" },
      { name: "Ruby", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/ruby.svg", url: "/services/software-development/ruby" },
      { name: "Lua", icon: "https://www.vectorlogo.zone/logos/lua/lua-icon.svg", url: "/services/software-development/lua" },
      { name: "Dart", icon: "https://www.vectorlogo.zone/logos/dartlang/dartlang-icon.svg", url: "/services/software-development/dart" },
      { name: "Assembly", icon: "https://raw.githubusercontent.com/get-icon/geticon/fc0f660daee147afb4a56c64e12bde6486b73e39/icons/assembly.svg", url: "/services/software-development/assembly" },
      { name: "Swift", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/swift.svg", url: "/services/software-development/swift" },
      { name: "R", icon: "https://www.vectorlogo.zone/logos/r-project/r-project-icon.svg", url: "/services/software-development/r" },
      { name: "Visual Basic", icon: "https://www.vectorlogo.zone/logos/microsoft_vb/microsoft_vb-icon.svg", url: "/services/software-development/visual-basic" },
      { name: "MATLAB", icon: "https://raw.githubusercontent.com/detain/svg-logos/07e36b4aa0691f3015886624395e083395e528c5/svg/m/matlab.svg", url: "/services/software-development/matlab" },
      // - { name: "VBA", icon: "https://www.vectorlogo.zone/logos/microsoft_vb/microsoft_vb-icon.svg", url: "/services/software-development/vba" },
      { name: "Groovy", icon: "https://www.vectorlogo.zone/logos/groovy-lang/groovy-lang-icon.svg", url: "/services/software-development/groovy" },
      { name: "Delphi", icon: "https://upload.wikimedia.org/wikipedia/en/b/b2/Embarcadero_Delphi_10.4_Sydney_Product_Logo_and_Icon.svg", url: "/services/software-development/delphi" },
      { name: "Scala", icon: "https://www.vectorlogo.zone/logos/scala-lang/scala-lang-icon.svg", url: "/services/software-development/scala" },
      { name: "Perl", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/perl.svg", url: "/services/software-development/perl" },
      { name: "Elixir", icon: "https://www.vectorlogo.zone/logos/elixir-lang/elixir-lang-icon.svg", url: "/services/software-development/elixir" },
      { name: "Objective-C", icon: "https://www.vectorlogo.zone/logos/apple_objectivec/apple_objectivec-icon.svg", url: "/services/software-development/objective-c" },
      { name: "Haskell", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/haskell-icon.svg", url: "/services/software-development/haskell" },
      { name: "GDScript", icon: "https://www.vectorlogo.zone/logos/godotengine/godotengine-icon.svg", url: "/services/software-development/gdscript" },
      { name: "Lisp", icon: "https://www.vectorlogo.zone/logos/common-lispnet/common-lispnet-icon.svg", url: "/services/software-development/lisp" },
      { name: "Solidity", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/solidity.svg", url: "/services/software-development/solidity" },
      { name: "Clojure", icon: "https://www.vectorlogo.zone/logos/clojure/clojure-icon.svg", url: "/services/software-development/clojure" },
      { name: "Julia", icon: "https://www.vectorlogo.zone/logos/julialang/julialang-icon.svg", url: "/services/software-development/julia" },
      { name: "Erlang", icon: "https://www.vectorlogo.zone/logos/erlang/erlang-icon.svg", url: "/services/software-development/erlang" },
      { name: "F#", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/fsharp.svg", url: "/services/software-development/fsharp" },
      { name: "Fortran", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/fortran.svg", url: "/services/software-development/fortran" },
      { name: "Prolog", icon: "https://raw.githubusercontent.com/vorillaz/devicons/ba75593fdf8d66496676a90cbf127d721f73e961/!SVG/prolog.svg", url: "/services/software-development/prolog" },
      { name: "Zig", icon: "https://www.vectorlogo.zone/logos/ziglang/ziglang-icon.svg", url: "/services/software-development/zig" },
      { name: "Elm", icon: "https://www.vectorlogo.zone/logos/elm-lang/elm-lang-icon.svg", url: "/services/software-development/elm" },
      { name: "Ada", icon: "https://upload.wikimedia.org/wikipedia/commons/3/31/Ada_horizon_green_logo_with_slogan.svg", url: "/services/software-development/ada" },
      { name: "OCaml", icon: "https://www.vectorlogo.zone/logos/ocaml/ocaml-icon.svg", url: "/services/software-development/ocaml" },
      // -Hard To ID- { name: "Apex", icon: "https://raw.githubusercontent.com/apexlang/apexlang.io/c5363f443d3c28275a46966b1fbcc40be6327ed4/static/img/icon.svg", url: "/services/software-development/apex" },
      { name: "COBOL", icon: "https://raw.githubusercontent.com/pheralb/svgl/c8a2b795bad955bca36088e810c94589f4ae8c79/static/library/cobol.svg", url: "/services/software-development/cobol" },
      { name: "SAS", icon: "https://www.vectorlogo.zone/logos/sas/sas-icon.svg", url: "/services/software-development/sas" },
      { name: "Crystal", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/crystal.svg", url: "/services/software-development/crystal" },
      // -Hard To ID-  { name: "Nim", icon: "https://www.vectorlogo.zone/logos/nim-lang/nim-lang-icon.svg", url: "/services/software-development/nim" },
      { name: "APL", icon: "https://raw.githubusercontent.com/devicons/devicon/6910f0503efdd315c8f9b858234310c06e04d9c0/icons/apl/apl-original.svg", url: "/services/software-development/apl" },
      // -Hard To ID- { name: "Flow", icon: "https://raw.githubusercontent.com/bestofjs/bestofjs/eb151f8eae67ee98fe070cd65284d11ccecaa20c/apps/bestofjs-nextjs/public/logos/flow.svg", url: "/services/software-development/flow" },
      { name: "Raku", icon: "https://upload.wikimedia.org/wikipedia/commons/8/85/Camelia.svg", url: "/services/software-development/raku" },
      // { name: "Vanilla JS", icon: "https://raw.githubusercontent.com/devicons/devicon/6910f0503efdd315c8f9b858234310c06e04d9c0/icons/javascript/javascript-original.svg", url: "/services/software-development/vanilla-js" },
      // ? {name: "Scheme", icon: "https://www.vectorlogo.zone/logos/scheme/scheme-icon.svg", url: "/services/software-development/scheme"},
      // ? {name: "Smalltalk", icon: "https://www.vectorlogo.zone/logos/smalltalk/smalltalk-icon.svg", url: "/services/software-development/smalltalk"},
      // ? {name: "Verilog", icon: "https://www.vectorlogo.zone/logos/verilog/verilog-icon.svg", url: "/services/software-development/verilog"},
      // ? {name: "VHDL", icon: "https://www.vectorlogo.zone/logos/vhdl/vhdl-icon.svg", url: "/services/software-development/vhdl"},
      // ? {name: "COBOL", icon: "https://www.vectorlogo.zone/logos/cobol/cobol-icon.svg", url: "/services/software-development/cobol"},
      // ? {name: "ABAP", icon: "https://www.vectorlogo.zone/logos/sap/sap-icon.svg", url: "/services/software-development/abap"},
      // ? {name: "Q#", icon: "https://www.vectorlogo.zone/logos/microsoft/microsoft-icon.svg", url: "/services/software-development/qsharp"},
      // ? {name: "K", icon: "https://www.vectorlogo.zone/logos/k/k-icon.svg", url: "/services/software-development/k"},
      // ? {name: "Pascal", icon: "https://www.vectorlogo.zone/logos/pascal/pascal-icon.svg", url: "/services/software-development/pascal"},
    ],
  },
  // {
  //   title: "SDKs & Libraries",
  //   items: [
  //       {name: "XCode", icon: "https://www.vectorlogo.zone/logos/apple_xcode/apple_xcode-icon.svg", url: "/services/software-development/xcode"},
  // {name:" MQTT"},
  // tableau
  // zend
  // ajax
  // axios
  // JAMstack
  // appypie
  //   ]
  // },
  {
    // title: "Full-Stack & Cross-platform Frameworks",
    title: "Web frameworks and technologies ",
    items: [
      { name: "Node.js", icon: "https://www.vectorlogo.zone/logos/nodejs/nodejs-icon.svg", url: "/services/software-development/nodejs" },
      { name: "React", icon: "https://www.vectorlogo.zone/logos/reactjs/reactjs-icon.svg", url: "/services/software-development/react" },
      { name: "jQuery", icon: "https://www.vectorlogo.zone/logos/jquery/jquery-icon.svg", url: "/services/software-development/jquery" },
      { name: "Express", icon: "https://www.vectorlogo.zone/logos/expressjs/expressjs-icon.svg", url: "/services/software-development/express" },
      { name: "Angular", icon: "https://www.vectorlogo.zone/logos/angular/angular-icon.svg", url: "/services/software-development/angular" },
      { name: "Next.js", icon: "https://cdn.worldvectorlogo.com/logos/next-js.svg", url: "/services/software-development/nextjs" },
      { name: "Microsoft .NET", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/dotnet.svg", url: "/services/software-development/dotnet" },
      { name: "Vue", icon: 'https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/vue.svg', url: "/services/software-development/vue" },
      { name: "Flask", icon: "https://www.vectorlogo.zone/logos/pocoo_flask/pocoo_flask-icon.svg", url: "/services/software-development/flask" },
      { name: "Spring", icon: "https://www.vectorlogo.zone/logos/springio/springio-icon.svg", url: "/services/software-development/spring" },
      { name: "Django", icon: "https://www.vectorlogo.zone/logos/djangoproject/djangoproject-icon.svg", url: "/services/software-development/django" },
      { name: "Laravel", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/laravel.svg", url: "/services/software-development/laravel" },
      { name: "FastAPI", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/fastapi-icon.svg", url: "/services/software-development/fastapi" },
      { name: "Svelte", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/svelte-icon.svg", url: "/services/software-development/svelte" },
      { name: "Ruby on Rails", icon: "https://raw.githubusercontent.com/dochne/wappalyzer/471c2fb0b093973c098bd1855b89c8cde4997479/src/images/icons/Ruby%20on%20Rails.svg", url: "/services/software-development/rubyonrails" },
      { name: "NestJS", icon: "https://www.vectorlogo.zone/logos/nestjs/nestjs-icon.svg", url: "/services/software-development/nestjs" },
      { name: "Blazor", icon: "https://raw.githubusercontent.com/detain/svg-logos/07e36b4aa0691f3015886624395e083395e528c5/svg/b/blazor.svg", url: "/services/software-development/blazor" },
      { name: "Nuxt.js", icon: "https://raw.githubusercontent.com/withastro/docs/42acee562f48ef2fbc33ff12a224a1ab5be4b7f9/public/logos/nuxtjs.svg", url: "/services/software-development/nuxtjs" },
      { name: "Symfony", icon: "https://www.vectorlogo.zone/logos/symfony/symfony-icon.svg", url: "/services/software-development/symfony" },
      { name: "Deno", icon: "https://www.vectorlogo.zone/logos/deno/deno-icon.svg", url: "/services/software-development/deno" },
      { name: "Gatsby", icon: "https://www.vectorlogo.zone/logos/gatsbyjs/gatsbyjs-icon.svg", url: "/services/software-development/gatsby" },
      { name: "Fastify", icon: "https://raw.githubusercontent.com/detain/svg-logos/07e36b4aa0691f3015886624395e083395e528c5/svg/f/fastify.svg", url: "/services/software-development/fastify" },
      { name: "Phoenix", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/phoenix.svg", url: "/services/software-development/phoenix" },
      { name: "CodeIgniter", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/codeigniter-icon.svg", url: "/services/software-development/codeigniter" },
      { name: "SolidJS", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/solidjs-icon.svg", url: "/services/software-development/solidjs" },
      { name: "Remix", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/remix-icon.svg", url: "/services/software-development/remix" },
      { name: "Play Framework", icon: "https://raw.githubusercontent.com/dochne/wappalyzer/471c2fb0b093973c098bd1855b89c8cde4997479/src/images/icons/Play.svg", url: "/services/software-development/play-framework" },
      { name: "Lit", icon: "https://raw.githubusercontent.com/dochne/wappalyzer/471c2fb0b093973c098bd1855b89c8cde4997479/src/images/icons/Lit.svg", url: "/services/software-development/lit" },
      { name: "Qwik", icon: "https://raw.githubusercontent.com/dochne/wappalyzer/471c2fb0b093973c098bd1855b89c8cde4997479/src/images/icons/Qwik.svg", url: "/services/software-development/qwik" },
      // {name: "Yii", icon: "https://www.vectorlogo.zone/logos/yiisoft/yiisoft-icon.svg", url: "/services/software-development/yii"},
      // {name: "Meteor", icon: "https://www.vectorlogo.zone/logos/meteor/meteor-icon.svg", url: "/services/software-development/meteor"},
      // {name: "Sapper", icon: "https://www.vectorlogo.zone/logos/sapper/sapper-icon.svg", url: "/services/software-development/sapper"},
      // {name: "Sails", icon: "https://www.vectorlogo.zone/logos/sails/sails-icon.svg", url: "/services/software-development/sails"},
      // {name: "Blade", icon: "https://www.vectorlogo.zone/logos/laravel/laravel-icon.svg", url: "/services/software-development/blade"},
      // { name: "Hugo", icon: "https://www.vectorlogo.zone/logos/gohugoio/gohugoio-icon.svg", url: "/services/software-development/hugo" },
      // // TODO: Move Flutter to Mobile Development
      // { name: "Flutter", icon: FlutterIcon },
      // { name: "And More", icon: BsThreeDots },
    ],
  },
  {
    title: "Databases",
    items: [
      { name: "PostgreSQL", icon: "https://www.vectorlogo.zone/logos/postgresql/postgresql-icon.svg", url: "/services/software-development/postgresql" },
      { name: "MySQL", icon: "https://www.vectorlogo.zone/logos/mysql/mysql-icon.svg", url: "/services/software-development/mysql" },
      { name: "SQLite", icon: "https://www.vectorlogo.zone/logos/sqlite/sqlite-icon.svg", url: "/services/software-development/sqlite" },
      { name: "MongoDB", icon: "https://www.vectorlogo.zone/logos/mongodb/mongodb-icon.svg", url: "/services/software-development/mongodb" },
      { name: "Microsoft SQL Server", icon: "https://raw.githubusercontent.com/cncf/landscape/a543f0ff114e9726d0818a22bbff0c1ac61dd3d1/hosted_logos/microsoft-sql-server.svg", url: "/services/software-development/microsoft-sql-server" },
      { name: "Redis", icon: "https://www.vectorlogo.zone/logos/redis/redis-icon.svg", url: "/services/software-development/redis" },
      { name: "MariaDB", icon: "https://www.vectorlogo.zone/logos/mariadb/mariadb-icon.svg", url: "/services/software-development/mariadb" },
      { name: "Elasticsearch", icon: "https://raw.githubusercontent.com/get-icon/geticon/fc0f660daee147afb4a56c64e12bde6486b73e39/icons/elasticsearch.svg", url: "/services/software-development/elasticsearch" },
      { name: "Oracle Database", icon: "https://raw.githubusercontent.com/dochne/wappalyzer/471c2fb0b093973c098bd1855b89c8cde4997479/src/images/icons/Oracle.svg", url: "/services/oracle/database" },
      { name: "DynamoDB", icon: "https://raw.githubusercontent.com/detain/svg-logos/07e36b4aa0691f3015886624395e083395e528c5/svg/a/aws-dynamodb.svg", url: "/services/aws/dynamodb" },
      // { name: "NoSQL", icon: "https://raw.githubusercontent.com/manuelbieh/logo-file-icons/6a172ce5a46ecfafe5db7f2ec624f4602cde9b8e/icons/database.svg", url: "/services/software-development/nosql" },
      // { name: "NewSQL", icon: "https://raw.githubusercontent.com/manuelbieh/logo-file-icons/6a172ce5a46ecfafe5db7f2ec624f4602cde9b8e/icons/database.svg", url: "/services/software-development/newsql" },
      // { name: "Neo4j", icon: "https://www.vectorlogo.zone/logos/neo4j/neo4j-icon.svg", url: "/services/software-development/neo4j" },
      // { name: "Firebase Realtime Database", icon: "https://www.vectorlogo.zone/logos/firebase/firebase-icon.svg", url: "/services/software-development/firebase-realtime-database" },
      // { name: "Cloud Firestore", icon: "https://www.vectorlogo.zone/logos/firebase/firebase-icon.svg", url: "/services/software-development/cloud-firestore" },
      // { name: "BigQuery", icon: "https://www.vectorlogo.zone/logos/google_cloud/google_cloud-icon.svg", url: "/services/software-development/bigquery" },
      // // -Hard to ID- { name: "Microsoft Access", icon: "https://www.vectorlogo.zone/logos/microsoft_access/microsoft_access-icon.svg", url: "/services/software-development/microsoft-access" },
      // { name: "H2 Database", icon: "https://upload.wikimedia.org/wikipedia/commons/a/a1/H2_logo.png", url: "/services/software-development/h2" },
      // { name: "Azure Cosmos DB", icon: "https://raw.githubusercontent.com/dochne/wappalyzer/471c2fb0b093973c098bd1855b89c8cde4997479/src/images/icons/Azure.svg", url: "/services/software-development/cosmos-db" },
      // { name: "Supabase", icon: "https://www.vectorlogo.zone/logos/supabase/supabase-icon.svg", url: "/services/software-development/supabase" },
      // { name: "InfluxDB", icon: "https://www.vectorlogo.zone/logos/influxdata/influxdata-icon.svg", url: "/services/software-development/influxdb" },
      // { name: "Cassandra", icon: "https://www.vectorlogo.zone/logos/apache_cassandra/apache_cassandra-icon.svg", url: "/services/software-development/cassandra" },
      // { name: "Snowflake", icon: "https://www.vectorlogo.zone/logos/snowflake/snowflake-icon.svg", url: "/services/software-development/snowflake" },
      // { name: "Neo4J", icon: "https://www.vectorlogo.zone/logos/neo4j/neo4j-icon.svg", url: "/services/software-development/neo4j" },
      // { name: "IBM DB2", icon: "https://www.vectorlogo.zone/logos/ibm_cloud/ibm_cloud-icon.svg", url: "/services/software-development/ibm-db2" },
      // { name: "Solr", icon: "https://www.vectorlogo.zone/logos/apache_solr/apache_solr-icon.svg", url: "/services/software-development/solr" },
      // { name: "FirebirdSQL", icon: "https://upload.wikimedia.org/wikipedia/de/0/00/Logo_FirebirdSQL.svg", url: "/services/software-development/firebird" },
      // { name: "Couch DB", icon: "https://www.vectorlogo.zone/logos/apache_couchdb/apache_couchdb-icon.svg", url: "/services/software-development/couchdb" },
      // { name: "Clickhouse", icon: "https://raw.githubusercontent.com/detain/svg-logos/07e36b4aa0691f3015886624395e083395e528c5/svg/c/clickhouse.svg", url: "/services/software-development/clickhouse" },
      // { name: "Cockroachdb", icon: "https://www.vectorlogo.zone/logos/cockroachlabs/cockroachlabs-icon.svg", url: "/services/software-development/cockroachdb" },
      // { name: "Couchbase", icon: "https://www.vectorlogo.zone/logos/couchbase/couchbase-icon.svg", url: "/services/software-development/couchbase" },
      // { name: "DuckDB", icon: "https://raw.githubusercontent.com/simple-icons/simple-icons/8a3731352af133a02223a6c7b1f37c4abb096af0/icons/duckdb.svg", url: "/services/software-development/duckdb" },
      // { name: "Datomic", icon: "https://upload.wikimedia.org/wikipedia/en/4/4a/Datomic_Logo.png", url: "/services/software-development/datomic" },
      // { name: "RavenDB", icon: "https://raw.githubusercontent.com/influxdata/ui/730f98f6581f367029374b158808479a5cf9e08c/src/writeData/graphics/ravendb.svg", url: "/services/software-development/ravendb" },
      // { name: "TiDB", icon: "https://raw.githubusercontent.com/cncf/landscape/a543f0ff114e9726d0818a22bbff0c1ac61dd3d1/hosted_logos/tidb.svg", url: "/services/software-development/tidb" },
    ]
  },
  {
    title: "CMS & E-Commerce",
    items: [
      { name: "WordPress", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/wordpress-icon.svg", url: "/services/software-development/wordpress" },
      { name: "Drupal", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/drupal-icon.svg", url: "/services/software-development/drupal" },
      // { name: "DotNetNuke", icon: "https://www.vectorlogo.zone/logos/dotnetnuke/dotnetnuke-icon.svg", url: "/services/software-development/dotnetnuke" },
      // { name: "ExpressionEngine", icon: "https://www.vectorlogo.zone/logos/expressionengine/expressionengine-icon.svg", url: "/services/software-development/expressionengine" },
      // { name: "Joomla", icon: "https://www.vectorlogo.zone/logos/joomla/joomla-icon.svg", url: "/services/software-development/joomla" },
      // { name: "Magento", icon: "https://www.vectorlogo.zone/logos/magento/magento-icon.svg", url: "/services/software-development/magento" },
      // { name: "Shopify", icon: "https://www.vectorlogo.zone/logos/shopify/shopify-icon.svg", url: "/services/software-development/shopify" },
      // { name: "WooCommerce", icon: "https://www.vectorlogo.zone/logos/woocommerce/woocommerce-icon.svg", url: "/services/software-development/woocommerce" },
      // { name: "PrestaShop", icon: "https://www.vectorlogo.zone/logos/prestashop/prestashop-icon.svg", url: "/services/software-development/prestashop" },
      // { name: "OpenCart", icon: "https://www.vectorlogo.zone/logos/opencart/opencart-icon.svg", url: "/services/software-development/opencart" },
      // { name: "BigCommerce", icon: "https://www.vectorlogo.zone/logos/bigcommerce/bigcommerce-icon.svg", url: "/services/software-development/bigcommerce" },
      // { name: "Squarespace", icon: "https://www.vectorlogo.zone/logos/squarespace/squarespace-icon.svg", url: "/services/software-development/squarespace" },
      // { name: "Wix", icon: "https://www.vectorlogo.zone/logos/wix/wix-icon.svg", url: "/services/software-development/wix" },
      // { name: "Weebly", icon: "https://www.vectorlogo.zone/logos/weebly/weebly-icon.svg", url: "/services/software-development/weebly" },
      // { name: "Webflow", icon: "https://www.vectorlogo.zone/logos/webflow/webflow-icon.svg", url: "/services/software-development/webflow" },
      // { name: "Ghost", icon: "https://www.vectorlogo.zone/logos/ghost/ghost-icon.svg", url: "/services/software-development/ghost" },
      // { name: "Contentful", icon: "https://www.vectorlogo.zone/logos/contentful/contentful-icon.svg", url: "/services/software-development/contentful" },
      // { name: "Strapi", icon: "https://www.vectorlogo.zone/logos/strapi/strapi-icon.svg", url: "/services/software-development/strapi" },
      // { name: "Netlify CMS", icon: "https://www.vectorlogo.zone/logos/netlify/netlify-icon.svg", url: "/services/software-development/netlify-cms" },
      // { name: "Sanity", icon: "https://www.vectorlogo.zone/logos/sanity/sanity-icon.svg", url: "/services/software-development/sanity" },
      // { name: "Prismic", icon: "https://www.vectorlogo.zone/logos/prismic/prismic-icon.svg", url: "/services/software-development/prismic" },
      // { name: "Craft CMS", icon: "https://www.vectorlogo.zone/logos/craftcms/craftcms-icon.svg", url: "/services/software-development/craft-cms" },
      // { name: "Umbraco", icon: "https://www.vectorlogo.zone/logos/umbraco/umbraco-icon.svg", url: "/services/software-development/umbraco" },
      // { name: "Kentico", icon: "https://www.vectorlogo.zone/logos/kentico/kentico-icon.svg", url: "/services/software-development/kentico" },
      // { name: "Sitecore", icon: "https://www.vectorlogo.zone/logos/sitecore/sitecore-icon.svg", url: "/services/software-development/sitecore" },
      // { name: "Shopware", icon: "https://www.vectorlogo.zone/logos/shopware/shopware-icon.svg", url: "/services/software-development/shopware" },
      // { name: "MODX", icon: "https://www.vectorlogo.zone/logos/modx/modx-icon.svg", url: "/services/software-development/modx" },
      // { name: "Textpattern", icon: "https://www.vectorlogo.zone/logos/textpattern/textpattern-icon.svg", url: "/services/software-development/textpattern" },
      // { name: "Bolt", icon: "https://www.vectorlogo.zone/logos/boltcms/boltcms-icon.svg", url: "/services/software-development/bolt" },
      // { name: "October CMS", icon: "https://www.vectorlogo.zone/logos/octobercms/octobercms-icon.svg", url: "/services/software-development/october-cms" },
      // { name: "Grav", icon: "https://www.vectorlogo.zone/logos/getgrav/getgrav-icon.svg", url: "/services/software-development/grav" },
      // { name: "Statamic", icon: "https://www.vectorlogo.zone/logos/statamic/statamic-icon.svg", url: "/services/software-development/statamic" },
      // cs-cart
      // 3d cart
      // volusion
    ],
  },
  // {
  //   title: "UI/UX & Frontend Tools, Technologies & Libraries",
  // NativeWind, TamaGUI, TailwindCSS, ETC.
  // UIKit, SwiftUI
  // },
  {
    name: "Other framworks and libraries",
    items: [
      { name: "React Native", icon: "https://www.vectorlogo.zone/logos/reactjs/reactjs-icon.svg", url: "/services/software-development/react-native" },
      // { name: "Tailwind CSS", icon: "https://www.vectorlogo.zone/logos/tailwindcss/tailwindcss-icon.svg", url: "/services/software-development/tailwindcss" },
      // { name: "Bootstrap", icon: "https://www.vectorlogo.zone/logos/getbootstrap/getbootstrap-icon.svg", url: "/services/software-development/bootstrap" },
      // { name: "Material-UI", icon: "https://www.vectorlogo.zone/logos/material-ui/material-ui-icon.svg", url: "/services/software-development/material-ui" },
      // { name: "Ant Design", icon: "https://www.vectorlogo.zone/logos/ant_design/ant_design-icon.svg", url: "/services/software-development/ant-design" },
      // { name: "Chakra UI", icon: "https://www.vectorlogo.zone/logos/chakra-ui/chakra-ui-icon.svg", url: "/services/software-development/chakra-ui" },
      // { name: "Vuetify", icon: "https://www.vectorlogo.zone/logos/vuetify/vuetify-icon.svg", url: "/services/software-development/vuetify" },
      // { name: "Bulma", icon: "https://www.vectorlogo.zone/logos/bulma/bulma-icon.svg", url: "/services/software-development/bulma" },
      // { name: "Semantic UI", icon: "https://www.vectorlogo.zone/logos/semantic-ui/semantic-ui-icon.svg", url: "/services/software-development/semantic-ui" },
      // { name: "Foundation", icon: "https://www.vectorlogo.zone/logos/zurb/zurb-icon.svg", url: "/services/software-development/foundation" },
      // { name: "Grommet", icon: "https://www.vectorlogo.zone/logos/grommet/grommet-icon.svg", url: "/services/software-development/grommet" },
      // { name: "Tailwind CSS", icon: "https://www.vectorlogo.zone/logos/tailwindcss/tailwindcss-icon.svg", url: "/services/software-development/tailwindcss" },
      // { name: "Buefy", icon: "https://www.vectorlogo.zone/logos/buefy/buefy-icon.svg", url: "/services/software-development/buefy" },
      // { name: "Quasar", icon: "https://www.vectorlogo.zone/logos/quasar-framework/quasar-framework
    ],
  },
  {
    title: "DevOps",
    items: [
      { name: "Docker", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/docker-icon.svg" },
      { name: "Kubernetes", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/kubernetes.svg" },
      { name: "GitLab CI/CD", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/gitlab.svg" },
      { name: "OpenShift", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/openshift.svg" },
      { name: "Grafana", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/grafana.svg" },
      // Stata
      // { name: "Jenkins", icon: "https://raw.githubusercontent.com/cncf/landscape/a543f0ff114e9726d0818a22bbff0c1ac61dd3d1/hosted_logos/jenkins.svg" },
      // { name: "Prometheus", icon: "https://raw.githubusercontent.com/cncf/landscape/a543f0ff114e9726d0818a22bbff0c1ac61dd3d1/hosted_logos/prometheus.svg" },
      // { name: "Terraform", icon: "https://raw.githubusercontent.com/cncf/landscape/a543f0ff114e9726d0818a22bbff0c1ac61dd3d1/hosted_logos/terraform.svg" },
      // { name: "Ansible", icon: "https://raw.githubusercontent.com/cncf/landscape/a543f0ff114e9726d0818a22bbff0c1ac61dd3d1/hosted_logos/ansible.svg" },
      // { name: "Puppet", icon: "https://raw.githubusercontent.com/cncf/landscape/a543f0ff114e9726d0818a22bbff0c1ac61dd3d1/hosted_logos/puppet.svg" },
      // { name: "Chef", icon: "https://raw.githubusercontent.com/cncf/landscape/a543f0ff114e9726d0818a22bbff0c1ac61dd3d1/hosted_logos/chef.svg" },
      // { name: "Vagrant", icon: "https://raw.githubusercontent.com/cncf/landscape/a543f0ff114e9726d0818a22bbff0c1ac61dd3d1/hosted_logos/vagrant.svg" },
      // { name: "Helm", icon: "https://raw.githubusercontent.com/cncf/landscape/a543f0ff114e9726d0818a22bbff0c1ac61dd3d1/hosted_logos/helm.svg" },
      // { name: "Rancher", icon: "https://raw.githubusercontent.com/cncf/landscape/a543f0ff114e9726d0818a22bbff0c1ac61dd3d1/hosted_logos/rancher.svg" },
      // { name: "Spinnaker", icon: "https://raw.githubusercontent.com/cncf/landscape/a543f0ff114e9726d0818a22bbff0c1ac61dd3d1/hosted_logos/spinnaker.svg" },
      // { name: "ArgoCD", icon: "https://raw.githubusercontent.com/argoproj/argo-cd/master/docs/assets/argocd-logo.png" },
      // { name: "Argo Workflows", icon: "https://raw.githubusercontent.com/argoproj/argo/master/docs/assets/argo.png" },
      // { name: "Argo Events", icon: "https://raw.githubusercontent.com/argoproj/argo-events/master/docs/assets/argo-events.png" },
      // { name: "Argo Rollouts", icon: "https://raw.githubusercontent.com/argoproj/argo-rollouts/master/docs/assets/argo-rollouts.png" },
      // { name: "Argo Tunnel", icon: "https://raw.githubusercontent.com/argoproj/argo-tunnel/master/docs/assets/argo-tunnel.png" },
      // { name: "Argo CD", icon: "https://raw.githubusercontent.com/argoproj/argo-cd/master/docs/assets/argocd-logo.png" },
      // { name: "Argo Rollouts", icon: "https://raw.githubusercontent.com/argoproj/argo-rollouts/master/docs/assets/argo-rollouts.png" },
      // { name: "Argo Events", icon: "https://raw.githubusercontent.com/argoproj/argo-events/master/docs/assets/argo-events.png" },
    ],
  },
  {
    title: "Clouds",
    items: [
      { name: "AWS", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/aws.svg" },
      { name: "Azure", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/microsoft-azure.svg" },
      { name: "Google Cloud", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/google-cloud.svg" },
      { name: "Akamai Cloud", icon: "https://raw.githubusercontent.com/dochne/wappalyzer/471c2fb0b093973c098bd1855b89c8cde4997479/src/images/icons/Akamai.svg" },
      { name: "DigitalOcean", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/digital-ocean-icon.svg" },
      { name: "Self Hosting", icon: "https://raw.githubusercontent.com/AwesomeLogos/google-cloud-icons/9fe9b31ddce5804ae4e6cf4d1bda5d5ee5ae6192/docs/images/game_servers.svg" },
      { name: "OCI", icon: "https://raw.githubusercontent.com/dochne/wappalyzer/471c2fb0b093973c098bd1855b89c8cde4997479/src/images/icons/Oracle.svg", url: "/services/oracle" },
      // { name: "Oracle Cloud Infrastructure", icon: "https://raw.githubusercontent.com/dochne/wappalyzer/471c2fb0b093973c098bd1855b89c8cde4997479/src/images/icons/Oracle.svg" },
    ],
  },
  {
    title: "Cybersecurity",
    items: [
      { name: "Cloudflare", icon: "https://raw.githubusercontent.com/gilbarbara/logos/52addcaa18dfecb4df77f3ee0753dca6b98187ad/logos/cloudflare-icon.svg" },
      { name: "Burp Suite", icon: "https://raw.githubusercontent.com/vinceliuice/Fluent-icon-theme/d56a03ec0d1be67353abbe293cb85a1ba25d2fad/src/scalable/apps/burp.svg" },
      { name: "Nmap", icon: "https://raw.githubusercontent.com/file-icons/icons/e6e6e6ac8cb1d91867167c228c00a667f4d47101/svg/Nmap.svg" },
      { name: "Wireshark", icon: "https://www.vectorlogo.zone/logos/wireshark/wireshark-icon.svg" },
      { name: "Metasploit", icon: "https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-icon-theme/f68510f72ebaa446a4d19133f3e8eee6288f7420/Papirus/64x64/apps/metasploit.svg" },
    ],
  },
  // {
  //   title: "AI & Machine Learning",
  // },
  // {
  //   title: "Data Science",
  //   items: [
  //     { name: "Jupyter", icon: "https://www.vectorlogo.zone/logos/jupyter/jupyter-icon.svg" },
  //     { name: "Pandas", icon: "https://www.vectorlogo.zone/logos/pandas/pandas-icon.svg" },
  //     { name: "NumPy", icon: "https://www.vectorlogo.zone/logos/numpy/numpy-icon.svg" },
  //     { name: "Matplotlib", icon: "https://www.vectorlogo.zone/logos/matplotlib/matplotlib-icon.svg" },
  //     { name: "Scikit-learn", icon: "https://www.vectorlogo.zone/logos/scikit-learn/scikit-learn-icon.svg" },
  //     { name: "TensorFlow", icon: "https://www.vectorlogo.zone/logos/tensorflow/tensorflow-icon.svg" },
  //     { name: "PyTorch", icon: "https://www.vectorlogo.zone/logos/pytorch/pytorch-icon.svg" },
  //     { name: "Keras", icon: "https://www.vectorlogo.zone/logos/keras/keras-icon.svg" },
  //     { name: "Seaborn", icon: "https://www.vectorlogo.zone/logos/seaborn/seaborn-icon.svg" },
  //     { name: "Plotly", icon: "https://www.vectorlogo.zone/logos/plotly/plotly-icon.svg" },
  //   ]
  // }

];
